### ISSUE TITLE
Add support for EU Region

### ISSUE THREAD

**Issue by drish** [drish/hyperb#12]
Hyper.sh just released EU region, gonna add support for it in the next couple days.

**Comment by anilgulecha** [comment]
Cool!

**Comment by anilgulecha** [comment]
Also, any chance the repo can support 2.1+ ruby?

**Comment by drish** [comment]
@anilgulecha i'm not sure yet what would be the impact of doing that, im gonna create a separated issue ticket and will do the proper testing 👍

**Comment by drish** [comment]
#13
